### ISSUE TITLE
Hide text/ Add icon, if no music is playing

### ISSUE THREAD

**Issue by Zer0xPoint** [aviwad/LyricFever#37]
It took lot of space from the menu bar, just to displaying that"Nothing Playing on Apple Music"

**Comment by aviwad** [comment]
What do you suggest it show instead?

**Comment by Zer0xPoint** [comment]
An icon maybe?

**Comment by aviwad** [comment]
<img width="292" alt="image" src="https://github.com/aviwad/LyricFever/assets/25706524/c02420dc-20f7-4de3-8dab-0e31b822f626">

Fixed :) Will be uploaded in a new version soon. Thank you for your feedback. Will close this when I release the DMG

**Comment by akulgoel96** [comment]
@aviwad I still can't seem to find this setting in the app, is this enabled in the test 2.1 version?

**Comment by aviwad** [comment]
Hi. This was implemented in v2.0

The app displays the music symbol in the menubar when Spotify is closed or if nothing is playing on Spotify (the now playing bar is empty). I am not sure if I understand you. This does NOT mean the symbol is shown when the music is paused. Paused != no song available. 

Would you prefer the icon be shown for when the song is paused?

**Comment by akulgoel96** [comment]
I would preferably want to just keep the icon in the menu bar to change settings and stuff since menu bar space in new macs is at a premium. Maybe this can be kept as a separate setting for people to toggle whether they want to see the song name or just the icon. I used to to use LyricsX in the past and I believe they also had this option.

**Comment by aviwad** [comment]
@akulgoel96 Ok. Could you confirm which scenarios you want just the menubar icon for? Just every scenario where my app displays the song name? (so this includes when no lyrics are available, or when lyrics are being displayed in karaoke/fullscreen, or when the song is paused)

**Comment by akulgoel96** [comment]
Yep, every scenario basically

**Comment by aviwad** [comment]
Fixed. Please wait for the 2.1 update
